sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=4.6.7
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=trunk

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=5.7.*"
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      WP_MULTISITE=1 phpunit
    fi
